version: '3.8'

services:
  dev-db:
    container_name: dev-db
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-nestjs}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
      TZ: 'America/Sao_Paulo'
      MYSQL_SSL_DISABLED: 'true'
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysql_data:
